sonata_admin:
    options:
        title_mode: single_text
    title: Admin Site

    templates:
        layout:  sonata_admin_layout.html.twig

    dashboard:
        groups:
            label_group_admin:
                roles: [ROLE_SONATA_ADMIN]

            sonata.admin.group.user:
                label: 'Пользователи'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group

    security:
        handler: sonata.admin.security.handler.role
        information:
            EDIT:   [EDIT]
            LIST:   [LIST]
            CREATE: [CREATE]
            VIEW:   [VIEW]
            DELETE: [DELETE]
            EXPORT: [EXPORT]
            EDIT_OWNER:   [EDIT_OWNER]
            VIEW_OWNER:   [VIEW_OWNER]
            DELETE_OWNER: [DELETE_OWNER]

    assets:
        javascripts:
            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js

            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonatacore/vendor/moment/locale/ru.js

            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js

            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js

            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js

            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js

            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js

            - bundles/sonataadmin/vendor/select2/select2.min.js

            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js

