fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     UserBundle\Entity\User

    group:
        group_class: UserBundle\Entity\Group

    service:
        mailer: fos_user.mailer.twig_swift

    from_email:
        address:     noreply@glavweb.ru
        sender_name: GLAVWEB
