fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     UserBundle\Entity\User

    group:
        group_class:   UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager
        mailer:       fos_user.mailer.twig_swift

    from_email:
        address:     noreply@glavweb.ru
        sender_name: GLAVWEB IS
